<?php

/**
 * @file
 * Contains vue_test.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function vue_test_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the vue_test module.
    case 'help.page.vue_test':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Vue test for custom module created using drupal console') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function vue_test_theme() {
  return [
    'vue_test' => [
      'render element' => 'children',
    ],
  ];
}

function vue_test_page_attachments(array &$pages) {
  $pages['#attached']['library'][] = 'vue_test/vue_test';
}
